name: FASTEN Model Checking Workflow Demo

on:
  push:
    branches:
      - master
      - main
      - 'maintenance/*'
  pull_request:
  workflow_dispatch:

permissions:
    contents: read
    checks: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Check Models
      run: |
        ./gradlew  \
          -Pgpr.user=${{github.actor}} -Pgpr.token=${{ secrets.GITHUB_TOKEN }}

    - name: Publish test report
      uses: mikepenz/action-junit-report@v4
      if: ${{ !cancelled() }}
      with:
        fail_on_failure: true
        require_tests: true
        report_paths: 'build/**/TEST*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
